version: "3"
services:
  pgAdmin:
    restart: always
    image: dpage/pgadmin4
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 1234@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - pgadmin:/var/lib/pgadmin
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgvol:/var/lib/postgresql/data
    depends_on:
      - pgAdmin
    environment:
      POSTGRES_PASSWORD: "bexs"
  backend:
    build: ./node/
    ports:
      - "4000:4000"
    volumes:
      - "./node:/usr/src/app"
    depends_on:
      - postgres
  frontend:
    build: ./react_app/
    ports:
      - "3000:3000"
    volumes:
      - "./react_app:/usr/src/app:cached"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    tty: true
    depends_on:
      - backend
volumes:
  pgvol:
  pgadmin:
